apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

images:
- name: ghcr.io/BenManifold/demo-app
  newTag: d175c8b3c6841899a5fb2e3ffb68f1935e07b994
- name: ghcr.io/benmanifold/demo-app
  newTag: latest
